---
- name: play practice file Management
  hosts: all
  vars:
    localtmp: /tmp/localfile
    remotetmp: /tmp/remotefile

  tasks:
    - name: creating/ removing a new file
      file:
        path: /home/admin/filebyplay
        state: file
        owner: root
        group: admin
        mode: u=rw,g=rw,o=x
        setype: httpd_sys_content_t

    - name: copying {{localtmp}} to remote managed nodes on {{remotetmp}}
      copy:
        src: "{{localtmp}}"
        dest: "{{remotetmp}}"

    - name: fetch (reverse copy) remote file to my control node
      fetch:
        src: "/tmp/remotefile2"
        dest: "/tmp/localdirectory"

    - name: synchronize local file to remote files as fsync command
      ansible.posix.synchronize:
        src: "{{localtmp}}"
        dest: "{{remotetmp}}"
      register: sync_results

    - debug:
        var: sync_results

