---
- name : play to practice handlers 
  hosts: all 
  tasks:
    - name : enabling password authentcation 
      copy :
        src: "/etc/ssh/sshd_config"
        dest: "/etc/ssh/sshd_config"
      notify: restart_sshd
  handlers: 
    - name: restart_sshd
      service:
        name : sshd
        state: restarted 
