---
- name: Dealing with AWS VPCs
  hosts: localhost
  gather_facts: no
  tasks:
    - name: create a VPC inside a region
      amazon.aws.ec2_vpc_net:
        name: Adisi_VPC
        cidr_block: 10.10.0.0/16
        region: us-east-1
        state: present 
      register: out1
    - debug: var=out1.vpc.id

    - name: List my VPCs inside a region without any filter
      amazon.aws.ec2_vpc_net_info:
      register: out2
    - debug:
        msg: " the vpc_id is {{ item.0.id }}"
      with_together:
        - "{{ out2.vpcs }}"
      
    - name: Gather information about a particular VPC using VPC ID
      amazon.aws.ec2_vpc_net_info:
        vpc_ids: vpc-0c671ccc3a0079e64
      register: filtered_vpc
    - debug: var=filtered_vpc.vpcs[0].id


